#version: "3.9"
services:
  bluesky-autopost:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: bluesky-autopost
    restart: unless-stopped
    environment:
      - TZ=Europe/Kyiv
      - OWM_API_KEY=${OWM_API_KEY}
      - CITY_ID=${CITY_ID}
      - COUNTRY_CODE=${COUNTRY_CODE}
      - BLUESKY_HANDLE=${BLUESKY_HANDLE}
      - BLUESKY_APP_PASSWORD=${BLUESKY_APP_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
